# -*- coding: utf-8 -*-
"""Cópia de BANCODEDADOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxK6sbxwsSOoJPeU5SA3BteZkuxMOeF4
"""

import numpy as np
import pandas as pd
import random

np.random.seed(42)

nomes = ["Ana", "Bruno", "Carlos", "Daniela", "Neemias", "Fernanda", "Gabriel", "Helena", "Igor", "Juliana", "Lucas", "Mariana", "Natan", "Olívia", "Pedro", "Rafael", "Sofia", "Tiago", "Beatriz", "Leonardo", "Larissa", "Gustavo", "Camila", "Rodrigo", "Letícia", "Ricardo", "Bárbara", "Matheus", "Amanda", "Vinícius"]
sobrenomes = ["Silva", "Santos", "Oliveira", "Souza", "Rodrigues", "Ferreira", "Alves", "Pereira", "Lima", "Gomes", "Costa", "Ribeiro", "Martins", "Carvalho", "Almeida", "Lopes", "Soares", "Fernandes", "Vieira", "Barbosa", "Rocha", "Dias", "Nascimento", "Andrade", "Moreira", "Nunes", "Marques", "Machado", "Mendes", "Freitas"]

nomes_gerados = np.random.choice(nomes, size=1000)
sobrenomes_gerados = np.random.choice(sobrenomes, size=1000)
nome_completo = np.char.add(np.char.add(nomes_gerados, " "), sobrenomes_gerados)


cpf = np.random.choice(np.arange(10000, 50000), size=1000, replace=False)



rua = np.random.choice(["Rua A", "Av B", "Alameda C", "Alameda D", "Alameda E"], size=1000)
estado = np.random.choice(["DF", "SP", "RJ", "MG", "PA"], size=1000)
bloco = np.random.choice(["L", "K", "J", "A", "O"], size=1000)

enderecos = np.char.add(np.char.add(np.char.add(np.char.add(rua, ", Bloco "), bloco), " - "), estado)

id_func = np.random.choice([0, 1, 2, 3, 4], size=1000, p=[0.2, 0.3, 0.39, 0.1, 0.01])


de_id_para_funcao = {0: 'Estagiario', 1: 'Junior', 2: 'Plenior', 3: 'Senior', 4: 'CEO'}
de_id_para_salario = {0: 1500, 1: 2000, 2: 4500, 3: 7000, 4: 10000}


func = [de_id_para_funcao[i] for i in id_func]
salary = [de_id_para_salario[i] for i in id_func]


qtd_telefones = np.random.choice([1, 2, 3], size=1000, p=[0.5, 0.35, 0.15])

telefone = []

for x in qtd_telefones:
    numeros = random.sample(range(900000000, 999999999), x)
    telefone.append(", ".join(map(str, numeros)))

dataDict = {
    "CPF": cpf,
    "Nome": nome_completo,
    "ID_FUNCAO": id_func,
    "Funcao": func,
    "Salario": salary,
    "Telefone": telefone,
    "Endereço": enderecos
}

df = pd.DataFrame(dataDict)


print(df.head(10))

print(df)

df.to_excel("DadosSinteticos.xlsx")



"""Agora o codigo foi baixado no formato xlsx. Para vizualizar ele forma mais limpa para verificar as redundancias, abra o google spreadsheet e importe o arquivo. Ele vai aparecer na esquerda da tela nas pastas do google collab"""